#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_RAPCHIEUPHIM")]
	public partial class QL_RAPPHIMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChucVu(ChucVu instance);
    partial void UpdateChucVu(ChucVu instance);
    partial void DeleteChucVu(ChucVu instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertCT_DoAn(CT_DoAn instance);
    partial void UpdateCT_DoAn(CT_DoAn instance);
    partial void DeleteCT_DoAn(CT_DoAn instance);
    partial void InsertCT_Ve(CT_Ve instance);
    partial void UpdateCT_Ve(CT_Ve instance);
    partial void DeleteCT_Ve(CT_Ve instance);
    partial void InsertDM_ManHinh(DM_ManHinh instance);
    partial void UpdateDM_ManHinh(DM_ManHinh instance);
    partial void DeleteDM_ManHinh(DM_ManHinh instance);
    partial void InsertDoAn(DoAn instance);
    partial void UpdateDoAn(DoAn instance);
    partial void DeleteDoAn(DoAn instance);
    partial void InsertGhe(Ghe instance);
    partial void UpdateGhe(Ghe instance);
    partial void DeleteGhe(Ghe instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertKhuyenMai(KhuyenMai instance);
    partial void UpdateKhuyenMai(KhuyenMai instance);
    partial void DeleteKhuyenMai(KhuyenMai instance);
    partial void InsertLichChieu(LichChieu instance);
    partial void UpdateLichChieu(LichChieu instance);
    partial void DeleteLichChieu(LichChieu instance);
    partial void InsertLoaiPhim(LoaiPhim instance);
    partial void UpdateLoaiPhim(LoaiPhim instance);
    partial void DeleteLoaiPhim(LoaiPhim instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertNhanVien_ChucVu(NhanVien_ChucVu instance);
    partial void UpdateNhanVien_ChucVu(NhanVien_ChucVu instance);
    partial void DeleteNhanVien_ChucVu(NhanVien_ChucVu instance);
    partial void InsertPhim(Phim instance);
    partial void UpdatePhim(Phim instance);
    partial void DeletePhim(Phim instance);
    partial void InsertPhim_LoaiPhim(Phim_LoaiPhim instance);
    partial void UpdatePhim_LoaiPhim(Phim_LoaiPhim instance);
    partial void DeletePhim_LoaiPhim(Phim_LoaiPhim instance);
    partial void InsertPhongChieu(PhongChieu instance);
    partial void UpdatePhongChieu(PhongChieu instance);
    partial void DeletePhongChieu(PhongChieu instance);
    #endregion
		
		public QL_RAPPHIMDataContext() : 
				base(global::DAL.Settings.Default.QL_RAPCHIEUPHIMConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public QL_RAPPHIMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_RAPPHIMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_RAPPHIMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_RAPPHIMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChucVu> ChucVus
		{
			get
			{
				return this.GetTable<ChucVu>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<CT_DoAn> CT_DoAns
		{
			get
			{
				return this.GetTable<CT_DoAn>();
			}
		}
		
		public System.Data.Linq.Table<CT_Ve> CT_Ves
		{
			get
			{
				return this.GetTable<CT_Ve>();
			}
		}
		
		public System.Data.Linq.Table<DM_ManHinh> DM_ManHinhs
		{
			get
			{
				return this.GetTable<DM_ManHinh>();
			}
		}
		
		public System.Data.Linq.Table<DoAn> DoAns
		{
			get
			{
				return this.GetTable<DoAn>();
			}
		}
		
		public System.Data.Linq.Table<Ghe> Ghes
		{
			get
			{
				return this.GetTable<Ghe>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<KhuyenMai> KhuyenMais
		{
			get
			{
				return this.GetTable<KhuyenMai>();
			}
		}
		
		public System.Data.Linq.Table<LichChieu> LichChieus
		{
			get
			{
				return this.GetTable<LichChieu>();
			}
		}
		
		public System.Data.Linq.Table<LoaiPhim> LoaiPhims
		{
			get
			{
				return this.GetTable<LoaiPhim>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien_ChucVu> NhanVien_ChucVus
		{
			get
			{
				return this.GetTable<NhanVien_ChucVu>();
			}
		}
		
		public System.Data.Linq.Table<PhanQuyen> PhanQuyens
		{
			get
			{
				return this.GetTable<PhanQuyen>();
			}
		}
		
		public System.Data.Linq.Table<Phim> Phims
		{
			get
			{
				return this.GetTable<Phim>();
			}
		}
		
		public System.Data.Linq.Table<Phim_LoaiPhim> Phim_LoaiPhims
		{
			get
			{
				return this.GetTable<Phim_LoaiPhim>();
			}
		}
		
		public System.Data.Linq.Table<PhongChieu> PhongChieus
		{
			get
			{
				return this.GetTable<PhongChieu>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChucVu")]
	public partial class ChucVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maChucVu;
		
		private string _tenChucVu;
		
		private EntitySet<NhanVien_ChucVu> _NhanVien_ChucVus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaChucVuChanging(string value);
    partial void OnmaChucVuChanged();
    partial void OntenChucVuChanging(string value);
    partial void OntenChucVuChanged();
    #endregion
		
		public ChucVu()
		{
			this._NhanVien_ChucVus = new EntitySet<NhanVien_ChucVu>(new Action<NhanVien_ChucVu>(this.attach_NhanVien_ChucVus), new Action<NhanVien_ChucVu>(this.detach_NhanVien_ChucVus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maChucVu", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maChucVu
		{
			get
			{
				return this._maChucVu;
			}
			set
			{
				if ((this._maChucVu != value))
				{
					this.OnmaChucVuChanging(value);
					this.SendPropertyChanging();
					this._maChucVu = value;
					this.SendPropertyChanged("maChucVu");
					this.OnmaChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenChucVu", DbType="NVarChar(255)")]
		public string tenChucVu
		{
			get
			{
				return this._tenChucVu;
			}
			set
			{
				if ((this._tenChucVu != value))
				{
					this.OntenChucVuChanging(value);
					this.SendPropertyChanging();
					this._tenChucVu = value;
					this.SendPropertyChanged("tenChucVu");
					this.OntenChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_NhanVien_ChucVu", Storage="_NhanVien_ChucVus", ThisKey="maChucVu", OtherKey="maChucVu")]
		public EntitySet<NhanVien_ChucVu> NhanVien_ChucVus
		{
			get
			{
				return this._NhanVien_ChucVus;
			}
			set
			{
				this._NhanVien_ChucVus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanVien_ChucVus(NhanVien_ChucVu entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = this;
		}
		
		private void detach_NhanVien_ChucVus(NhanVien_ChucVu entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _tenDangNhap;
		
		private string _pass;
		
		private System.Nullable<int> _hoatDong;
		
		private string _maNhanVien;
		
		private EntitySet<NhanVien_ChucVu> _NhanVien_ChucVus;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntenDangNhapChanging(string value);
    partial void OntenDangNhapChanged();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    partial void OnhoatDongChanging(System.Nullable<int> value);
    partial void OnhoatDongChanged();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._NhanVien_ChucVus = new EntitySet<NhanVien_ChucVu>(new Action<NhanVien_ChucVu>(this.attach_NhanVien_ChucVus), new Action<NhanVien_ChucVu>(this.detach_NhanVien_ChucVus));
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenDangNhap", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string tenDangNhap
		{
			get
			{
				return this._tenDangNhap;
			}
			set
			{
				if ((this._tenDangNhap != value))
				{
					this.OntenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._tenDangNhap = value;
					this.SendPropertyChanged("tenDangNhap");
					this.OntenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="NVarChar(255)")]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoatDong", DbType="Int")]
		public System.Nullable<int> hoatDong
		{
			get
			{
				return this._hoatDong;
			}
			set
			{
				if ((this._hoatDong != value))
				{
					this.OnhoatDongChanging(value);
					this.SendPropertyChanging();
					this._hoatDong = value;
					this.SendPropertyChanged("hoatDong");
					this.OnhoatDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="VarChar(10)")]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_NhanVien_ChucVu", Storage="_NhanVien_ChucVus", ThisKey="tenDangNhap", OtherKey="tenDangNhap")]
		public EntitySet<NhanVien_ChucVu> NhanVien_ChucVus
		{
			get
			{
				return this._NhanVien_ChucVus;
			}
			set
			{
				this._NhanVien_ChucVus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaiKhoan", Storage="_NhanVien", ThisKey="maNhanVien", OtherKey="maNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._maNhanVien = value.maNhanVien;
					}
					else
					{
						this._maNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanVien_ChucVus(NhanVien_ChucVu entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = this;
		}
		
		private void detach_NhanVien_ChucVus(NhanVien_ChucVu entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_DoAn")]
	public partial class CT_DoAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHD;
		
		private string _maDoAn;
		
		private System.Nullable<int> _soLuong;
		
		private System.Nullable<decimal> _thanhTien;
		
		private EntityRef<DoAn> _DoAn;
		
		private EntityRef<HoaDon> _HoaDon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHDChanging(string value);
    partial void OnmaHDChanged();
    partial void OnmaDoAnChanging(string value);
    partial void OnmaDoAnChanged();
    partial void OnsoLuongChanging(System.Nullable<int> value);
    partial void OnsoLuongChanged();
    partial void OnthanhTienChanging(System.Nullable<decimal> value);
    partial void OnthanhTienChanged();
    #endregion
		
		public CT_DoAn()
		{
			this._DoAn = default(EntityRef<DoAn>);
			this._HoaDon = default(EntityRef<HoaDon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHD", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHD
		{
			get
			{
				return this._maHD;
			}
			set
			{
				if ((this._maHD != value))
				{
					if (this._HoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHDChanging(value);
					this.SendPropertyChanging();
					this._maHD = value;
					this.SendPropertyChanged("maHD");
					this.OnmaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDoAn", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maDoAn
		{
			get
			{
				return this._maDoAn;
			}
			set
			{
				if ((this._maDoAn != value))
				{
					if (this._DoAn.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaDoAnChanging(value);
					this.SendPropertyChanging();
					this._maDoAn = value;
					this.SendPropertyChanged("maDoAn");
					this.OnmaDoAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhTien", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> thanhTien
		{
			get
			{
				return this._thanhTien;
			}
			set
			{
				if ((this._thanhTien != value))
				{
					this.OnthanhTienChanging(value);
					this.SendPropertyChanging();
					this._thanhTien = value;
					this.SendPropertyChanged("thanhTien");
					this.OnthanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DoAn_CT_DoAn", Storage="_DoAn", ThisKey="maDoAn", OtherKey="maDoAn", IsForeignKey=true)]
		public DoAn DoAn
		{
			get
			{
				return this._DoAn.Entity;
			}
			set
			{
				DoAn previousValue = this._DoAn.Entity;
				if (((previousValue != value) 
							|| (this._DoAn.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DoAn.Entity = null;
						previousValue.CT_DoAns.Remove(this);
					}
					this._DoAn.Entity = value;
					if ((value != null))
					{
						value.CT_DoAns.Add(this);
						this._maDoAn = value.maDoAn;
					}
					else
					{
						this._maDoAn = default(string);
					}
					this.SendPropertyChanged("DoAn");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_CT_DoAn", Storage="_HoaDon", ThisKey="maHD", OtherKey="maHD", IsForeignKey=true)]
		public HoaDon HoaDon
		{
			get
			{
				return this._HoaDon.Entity;
			}
			set
			{
				HoaDon previousValue = this._HoaDon.Entity;
				if (((previousValue != value) 
							|| (this._HoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDon.Entity = null;
						previousValue.CT_DoAns.Remove(this);
					}
					this._HoaDon.Entity = value;
					if ((value != null))
					{
						value.CT_DoAns.Add(this);
						this._maHD = value.maHD;
					}
					else
					{
						this._maHD = default(string);
					}
					this.SendPropertyChanged("HoaDon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_Ve")]
	public partial class CT_Ve : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHD;
		
		private string _maGhe;
		
		private string _maLichChieu;
		
		private EntityRef<Ghe> _Ghe;
		
		private EntityRef<HoaDon> _HoaDon;
		
		private EntityRef<LichChieu> _LichChieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHDChanging(string value);
    partial void OnmaHDChanged();
    partial void OnmaGheChanging(string value);
    partial void OnmaGheChanged();
    partial void OnmaLichChieuChanging(string value);
    partial void OnmaLichChieuChanged();
    #endregion
		
		public CT_Ve()
		{
			this._Ghe = default(EntityRef<Ghe>);
			this._HoaDon = default(EntityRef<HoaDon>);
			this._LichChieu = default(EntityRef<LichChieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHD", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHD
		{
			get
			{
				return this._maHD;
			}
			set
			{
				if ((this._maHD != value))
				{
					if (this._HoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHDChanging(value);
					this.SendPropertyChanging();
					this._maHD = value;
					this.SendPropertyChanged("maHD");
					this.OnmaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maGhe", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maGhe
		{
			get
			{
				return this._maGhe;
			}
			set
			{
				if ((this._maGhe != value))
				{
					if (this._Ghe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaGheChanging(value);
					this.SendPropertyChanging();
					this._maGhe = value;
					this.SendPropertyChanged("maGhe");
					this.OnmaGheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLichChieu", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLichChieu
		{
			get
			{
				return this._maLichChieu;
			}
			set
			{
				if ((this._maLichChieu != value))
				{
					if (this._LichChieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLichChieuChanging(value);
					this.SendPropertyChanging();
					this._maLichChieu = value;
					this.SendPropertyChanged("maLichChieu");
					this.OnmaLichChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ghe_CT_Ve", Storage="_Ghe", ThisKey="maGhe", OtherKey="maGhe", IsForeignKey=true)]
		public Ghe Ghe
		{
			get
			{
				return this._Ghe.Entity;
			}
			set
			{
				Ghe previousValue = this._Ghe.Entity;
				if (((previousValue != value) 
							|| (this._Ghe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ghe.Entity = null;
						previousValue.CT_Ves.Remove(this);
					}
					this._Ghe.Entity = value;
					if ((value != null))
					{
						value.CT_Ves.Add(this);
						this._maGhe = value.maGhe;
					}
					else
					{
						this._maGhe = default(string);
					}
					this.SendPropertyChanged("Ghe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_CT_Ve", Storage="_HoaDon", ThisKey="maHD", OtherKey="maHD", IsForeignKey=true)]
		public HoaDon HoaDon
		{
			get
			{
				return this._HoaDon.Entity;
			}
			set
			{
				HoaDon previousValue = this._HoaDon.Entity;
				if (((previousValue != value) 
							|| (this._HoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDon.Entity = null;
						previousValue.CT_Ves.Remove(this);
					}
					this._HoaDon.Entity = value;
					if ((value != null))
					{
						value.CT_Ves.Add(this);
						this._maHD = value.maHD;
					}
					else
					{
						this._maHD = default(string);
					}
					this.SendPropertyChanged("HoaDon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichChieu_CT_Ve", Storage="_LichChieu", ThisKey="maLichChieu", OtherKey="maLichChieu", IsForeignKey=true)]
		public LichChieu LichChieu
		{
			get
			{
				return this._LichChieu.Entity;
			}
			set
			{
				LichChieu previousValue = this._LichChieu.Entity;
				if (((previousValue != value) 
							|| (this._LichChieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LichChieu.Entity = null;
						previousValue.CT_Ves.Remove(this);
					}
					this._LichChieu.Entity = value;
					if ((value != null))
					{
						value.CT_Ves.Add(this);
						this._maLichChieu = value.maLichChieu;
					}
					else
					{
						this._maLichChieu = default(string);
					}
					this.SendPropertyChanged("LichChieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DM_ManHinh")]
	public partial class DM_ManHinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maManHinh;
		
		private string _tenManHinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaManHinhChanging(string value);
    partial void OnmaManHinhChanged();
    partial void OntenManHinhChanging(string value);
    partial void OntenManHinhChanged();
    #endregion
		
		public DM_ManHinh()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maManHinh", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maManHinh
		{
			get
			{
				return this._maManHinh;
			}
			set
			{
				if ((this._maManHinh != value))
				{
					this.OnmaManHinhChanging(value);
					this.SendPropertyChanging();
					this._maManHinh = value;
					this.SendPropertyChanged("maManHinh");
					this.OnmaManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenManHinh", DbType="NVarChar(255)")]
		public string tenManHinh
		{
			get
			{
				return this._tenManHinh;
			}
			set
			{
				if ((this._tenManHinh != value))
				{
					this.OntenManHinhChanging(value);
					this.SendPropertyChanging();
					this._tenManHinh = value;
					this.SendPropertyChanged("tenManHinh");
					this.OntenManHinhChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoAn")]
	public partial class DoAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maDoAn;
		
		private string _tenDoAn;
		
		private System.Nullable<decimal> _donGia;
		
		private string _hinhAnh;
		
		private System.Nullable<int> _soLuong;
		
		private System.Nullable<int> _trangThai;
		
		private EntitySet<CT_DoAn> _CT_DoAns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaDoAnChanging(string value);
    partial void OnmaDoAnChanged();
    partial void OntenDoAnChanging(string value);
    partial void OntenDoAnChanged();
    partial void OndonGiaChanging(System.Nullable<decimal> value);
    partial void OndonGiaChanged();
    partial void OnhinhAnhChanging(string value);
    partial void OnhinhAnhChanged();
    partial void OnsoLuongChanging(System.Nullable<int> value);
    partial void OnsoLuongChanged();
    partial void OntrangThaiChanging(System.Nullable<int> value);
    partial void OntrangThaiChanged();
    #endregion
		
		public DoAn()
		{
			this._CT_DoAns = new EntitySet<CT_DoAn>(new Action<CT_DoAn>(this.attach_CT_DoAns), new Action<CT_DoAn>(this.detach_CT_DoAns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDoAn", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maDoAn
		{
			get
			{
				return this._maDoAn;
			}
			set
			{
				if ((this._maDoAn != value))
				{
					this.OnmaDoAnChanging(value);
					this.SendPropertyChanging();
					this._maDoAn = value;
					this.SendPropertyChanged("maDoAn");
					this.OnmaDoAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenDoAn", DbType="NVarChar(255)")]
		public string tenDoAn
		{
			get
			{
				return this._tenDoAn;
			}
			set
			{
				if ((this._tenDoAn != value))
				{
					this.OntenDoAnChanging(value);
					this.SendPropertyChanging();
					this._tenDoAn = value;
					this.SendPropertyChanged("tenDoAn");
					this.OntenDoAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donGia", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> donGia
		{
			get
			{
				return this._donGia;
			}
			set
			{
				if ((this._donGia != value))
				{
					this.OndonGiaChanging(value);
					this.SendPropertyChanging();
					this._donGia = value;
					this.SendPropertyChanged("donGia");
					this.OndonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhAnh", DbType="NVarChar(255)")]
		public string hinhAnh
		{
			get
			{
				return this._hinhAnh;
			}
			set
			{
				if ((this._hinhAnh != value))
				{
					this.OnhinhAnhChanging(value);
					this.SendPropertyChanging();
					this._hinhAnh = value;
					this.SendPropertyChanged("hinhAnh");
					this.OnhinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Int")]
		public System.Nullable<int> trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DoAn_CT_DoAn", Storage="_CT_DoAns", ThisKey="maDoAn", OtherKey="maDoAn")]
		public EntitySet<CT_DoAn> CT_DoAns
		{
			get
			{
				return this._CT_DoAns;
			}
			set
			{
				this._CT_DoAns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_DoAns(CT_DoAn entity)
		{
			this.SendPropertyChanging();
			entity.DoAn = this;
		}
		
		private void detach_CT_DoAns(CT_DoAn entity)
		{
			this.SendPropertyChanging();
			entity.DoAn = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ghe")]
	public partial class Ghe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maGhe;
		
		private string _maPhongChieu;
		
		private string _cots;
		
		private string _hang;
		
		private string _loaiGhe;
		
		private System.Nullable<int> _trangThai;
		
		private System.Nullable<decimal> _gia;
		
		private EntitySet<CT_Ve> _CT_Ves;
		
		private EntityRef<PhongChieu> _PhongChieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaGheChanging(string value);
    partial void OnmaGheChanged();
    partial void OnmaPhongChieuChanging(string value);
    partial void OnmaPhongChieuChanged();
    partial void OncotsChanging(string value);
    partial void OncotsChanged();
    partial void OnhangChanging(string value);
    partial void OnhangChanged();
    partial void OnloaiGheChanging(string value);
    partial void OnloaiGheChanged();
    partial void OntrangThaiChanging(System.Nullable<int> value);
    partial void OntrangThaiChanged();
    partial void OngiaChanging(System.Nullable<decimal> value);
    partial void OngiaChanged();
    #endregion
		
		public Ghe()
		{
			this._CT_Ves = new EntitySet<CT_Ve>(new Action<CT_Ve>(this.attach_CT_Ves), new Action<CT_Ve>(this.detach_CT_Ves));
			this._PhongChieu = default(EntityRef<PhongChieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maGhe", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maGhe
		{
			get
			{
				return this._maGhe;
			}
			set
			{
				if ((this._maGhe != value))
				{
					this.OnmaGheChanging(value);
					this.SendPropertyChanging();
					this._maGhe = value;
					this.SendPropertyChanged("maGhe");
					this.OnmaGheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhongChieu", DbType="VarChar(10)")]
		public string maPhongChieu
		{
			get
			{
				return this._maPhongChieu;
			}
			set
			{
				if ((this._maPhongChieu != value))
				{
					if (this._PhongChieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaPhongChieuChanging(value);
					this.SendPropertyChanging();
					this._maPhongChieu = value;
					this.SendPropertyChanged("maPhongChieu");
					this.OnmaPhongChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cots", DbType="VarChar(5)")]
		public string cots
		{
			get
			{
				return this._cots;
			}
			set
			{
				if ((this._cots != value))
				{
					this.OncotsChanging(value);
					this.SendPropertyChanging();
					this._cots = value;
					this.SendPropertyChanged("cots");
					this.OncotsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hang", DbType="VarChar(5)")]
		public string hang
		{
			get
			{
				return this._hang;
			}
			set
			{
				if ((this._hang != value))
				{
					this.OnhangChanging(value);
					this.SendPropertyChanging();
					this._hang = value;
					this.SendPropertyChanged("hang");
					this.OnhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiGhe", DbType="NVarChar(50)")]
		public string loaiGhe
		{
			get
			{
				return this._loaiGhe;
			}
			set
			{
				if ((this._loaiGhe != value))
				{
					this.OnloaiGheChanging(value);
					this.SendPropertyChanging();
					this._loaiGhe = value;
					this.SendPropertyChanged("loaiGhe");
					this.OnloaiGheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Int")]
		public System.Nullable<int> trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ghe_CT_Ve", Storage="_CT_Ves", ThisKey="maGhe", OtherKey="maGhe")]
		public EntitySet<CT_Ve> CT_Ves
		{
			get
			{
				return this._CT_Ves;
			}
			set
			{
				this._CT_Ves.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongChieu_Ghe", Storage="_PhongChieu", ThisKey="maPhongChieu", OtherKey="maPhongChieu", IsForeignKey=true)]
		public PhongChieu PhongChieu
		{
			get
			{
				return this._PhongChieu.Entity;
			}
			set
			{
				PhongChieu previousValue = this._PhongChieu.Entity;
				if (((previousValue != value) 
							|| (this._PhongChieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongChieu.Entity = null;
						previousValue.Ghes.Remove(this);
					}
					this._PhongChieu.Entity = value;
					if ((value != null))
					{
						value.Ghes.Add(this);
						this._maPhongChieu = value.maPhongChieu;
					}
					else
					{
						this._maPhongChieu = default(string);
					}
					this.SendPropertyChanged("PhongChieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_Ves(CT_Ve entity)
		{
			this.SendPropertyChanging();
			entity.Ghe = this;
		}
		
		private void detach_CT_Ves(CT_Ve entity)
		{
			this.SendPropertyChanging();
			entity.Ghe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHD;
		
		private string _maNV;
		
		private string _maKH;
		
		private System.Nullable<System.DateTime> _ngayBan;
		
		private System.Nullable<decimal> _tongTien;
		
		private string _maKhuyenMai;
		
		private EntitySet<CT_DoAn> _CT_DoAns;
		
		private EntitySet<CT_Ve> _CT_Ves;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<KhuyenMai> _KhuyenMai;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHDChanging(string value);
    partial void OnmaHDChanged();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OnmaKHChanging(string value);
    partial void OnmaKHChanged();
    partial void OnngayBanChanging(System.Nullable<System.DateTime> value);
    partial void OnngayBanChanged();
    partial void OntongTienChanging(System.Nullable<decimal> value);
    partial void OntongTienChanged();
    partial void OnmaKhuyenMaiChanging(string value);
    partial void OnmaKhuyenMaiChanged();
    #endregion
		
		public HoaDon()
		{
			this._CT_DoAns = new EntitySet<CT_DoAn>(new Action<CT_DoAn>(this.attach_CT_DoAns), new Action<CT_DoAn>(this.detach_CT_DoAns));
			this._CT_Ves = new EntitySet<CT_Ve>(new Action<CT_Ve>(this.attach_CT_Ves), new Action<CT_Ve>(this.detach_CT_Ves));
			this._KhachHang = default(EntityRef<KhachHang>);
			this._KhuyenMai = default(EntityRef<KhuyenMai>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHD", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHD
		{
			get
			{
				return this._maHD;
			}
			set
			{
				if ((this._maHD != value))
				{
					this.OnmaHDChanging(value);
					this.SendPropertyChanging();
					this._maHD = value;
					this.SendPropertyChanged("maHD");
					this.OnmaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="VarChar(10)")]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="VarChar(10)")]
		public string maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayBan", DbType="Date")]
		public System.Nullable<System.DateTime> ngayBan
		{
			get
			{
				return this._ngayBan;
			}
			set
			{
				if ((this._ngayBan != value))
				{
					this.OnngayBanChanging(value);
					this.SendPropertyChanging();
					this._ngayBan = value;
					this.SendPropertyChanged("ngayBan");
					this.OnngayBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongTien", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> tongTien
		{
			get
			{
				return this._tongTien;
			}
			set
			{
				if ((this._tongTien != value))
				{
					this.OntongTienChanging(value);
					this.SendPropertyChanging();
					this._tongTien = value;
					this.SendPropertyChanged("tongTien");
					this.OntongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhuyenMai", DbType="VarChar(10)")]
		public string maKhuyenMai
		{
			get
			{
				return this._maKhuyenMai;
			}
			set
			{
				if ((this._maKhuyenMai != value))
				{
					if (this._KhuyenMai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._maKhuyenMai = value;
					this.SendPropertyChanged("maKhuyenMai");
					this.OnmaKhuyenMaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_CT_DoAn", Storage="_CT_DoAns", ThisKey="maHD", OtherKey="maHD")]
		public EntitySet<CT_DoAn> CT_DoAns
		{
			get
			{
				return this._CT_DoAns;
			}
			set
			{
				this._CT_DoAns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_CT_Ve", Storage="_CT_Ves", ThisKey="maHD", OtherKey="maHD")]
		public EntitySet<CT_Ve> CT_Ves
		{
			get
			{
				return this._CT_Ves;
			}
			set
			{
				this._CT_Ves.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDon", Storage="_KhachHang", ThisKey="maKH", OtherKey="maKhachHang", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._maKH = value.maKhachHang;
					}
					else
					{
						this._maKH = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhuyenMai_HoaDon", Storage="_KhuyenMai", ThisKey="maKhuyenMai", OtherKey="maKhuyenMai", IsForeignKey=true)]
		public KhuyenMai KhuyenMai
		{
			get
			{
				return this._KhuyenMai.Entity;
			}
			set
			{
				KhuyenMai previousValue = this._KhuyenMai.Entity;
				if (((previousValue != value) 
							|| (this._KhuyenMai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhuyenMai.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._KhuyenMai.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._maKhuyenMai = value.maKhuyenMai;
					}
					else
					{
						this._maKhuyenMai = default(string);
					}
					this.SendPropertyChanged("KhuyenMai");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon", Storage="_NhanVien", ThisKey="maNV", OtherKey="maNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._maNV = value.maNhanVien;
					}
					else
					{
						this._maNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_DoAns(CT_DoAn entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = this;
		}
		
		private void detach_CT_DoAns(CT_DoAn entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = null;
		}
		
		private void attach_CT_Ves(CT_Ve entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = this;
		}
		
		private void detach_CT_Ves(CT_Ve entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maKhachHang;
		
		private string _tenKhachHang;
		
		private string _diaChi;
		
		private string _email;
		
		private string _SDT;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKhachHangChanging(string value);
    partial void OnmaKhachHangChanged();
    partial void OntenKhachHangChanging(string value);
    partial void OntenKhachHangChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    #endregion
		
		public KhachHang()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhachHang", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKhachHang
		{
			get
			{
				return this._maKhachHang;
			}
			set
			{
				if ((this._maKhachHang != value))
				{
					this.OnmaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._maKhachHang = value;
					this.SendPropertyChanged("maKhachHang");
					this.OnmaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKhachHang", DbType="NVarChar(255)")]
		public string tenKhachHang
		{
			get
			{
				return this._tenKhachHang;
			}
			set
			{
				if ((this._tenKhachHang != value))
				{
					this.OntenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._tenKhachHang = value;
					this.SendPropertyChanged("tenKhachHang");
					this.OntenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(255)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(255)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(15)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDon", Storage="_HoaDons", ThisKey="maKhachHang", OtherKey="maKH")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhuyenMai")]
	public partial class KhuyenMai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maKhuyenMai;
		
		private string _tenKM;
		
		private System.Nullable<System.DateTime> _thoiGianBD;
		
		private System.Nullable<System.DateTime> _thoiGianKT;
		
		private System.Nullable<decimal> _phanTramKhuyenMai;
		
		private System.Nullable<int> _trangThai;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKhuyenMaiChanging(string value);
    partial void OnmaKhuyenMaiChanged();
    partial void OntenKMChanging(string value);
    partial void OntenKMChanged();
    partial void OnthoiGianBDChanging(System.Nullable<System.DateTime> value);
    partial void OnthoiGianBDChanged();
    partial void OnthoiGianKTChanging(System.Nullable<System.DateTime> value);
    partial void OnthoiGianKTChanged();
    partial void OnphanTramKhuyenMaiChanging(System.Nullable<decimal> value);
    partial void OnphanTramKhuyenMaiChanged();
    partial void OntrangThaiChanging(System.Nullable<int> value);
    partial void OntrangThaiChanged();
    #endregion
		
		public KhuyenMai()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhuyenMai", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKhuyenMai
		{
			get
			{
				return this._maKhuyenMai;
			}
			set
			{
				if ((this._maKhuyenMai != value))
				{
					this.OnmaKhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._maKhuyenMai = value;
					this.SendPropertyChanged("maKhuyenMai");
					this.OnmaKhuyenMaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKM", DbType="NVarChar(255)")]
		public string tenKM
		{
			get
			{
				return this._tenKM;
			}
			set
			{
				if ((this._tenKM != value))
				{
					this.OntenKMChanging(value);
					this.SendPropertyChanging();
					this._tenKM = value;
					this.SendPropertyChanged("tenKM");
					this.OntenKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiGianBD", DbType="Date")]
		public System.Nullable<System.DateTime> thoiGianBD
		{
			get
			{
				return this._thoiGianBD;
			}
			set
			{
				if ((this._thoiGianBD != value))
				{
					this.OnthoiGianBDChanging(value);
					this.SendPropertyChanging();
					this._thoiGianBD = value;
					this.SendPropertyChanged("thoiGianBD");
					this.OnthoiGianBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiGianKT", DbType="Date")]
		public System.Nullable<System.DateTime> thoiGianKT
		{
			get
			{
				return this._thoiGianKT;
			}
			set
			{
				if ((this._thoiGianKT != value))
				{
					this.OnthoiGianKTChanging(value);
					this.SendPropertyChanging();
					this._thoiGianKT = value;
					this.SendPropertyChanged("thoiGianKT");
					this.OnthoiGianKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phanTramKhuyenMai", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> phanTramKhuyenMai
		{
			get
			{
				return this._phanTramKhuyenMai;
			}
			set
			{
				if ((this._phanTramKhuyenMai != value))
				{
					this.OnphanTramKhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._phanTramKhuyenMai = value;
					this.SendPropertyChanged("phanTramKhuyenMai");
					this.OnphanTramKhuyenMaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Int")]
		public System.Nullable<int> trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhuyenMai_HoaDon", Storage="_HoaDons", ThisKey="maKhuyenMai", OtherKey="maKhuyenMai")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhuyenMai = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhuyenMai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichChieu")]
	public partial class LichChieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maLichChieu;
		
		private string _maPhim;
		
		private string _maPhongChieu;
		
		private System.Nullable<System.DateTime> _ngayChieu;
		
		private System.Nullable<System.TimeSpan> _gioBD;
		
		private System.Nullable<System.TimeSpan> _gioKT;
		
		private EntitySet<CT_Ve> _CT_Ves;
		
		private EntityRef<Phim> _Phim;
		
		private EntityRef<PhongChieu> _PhongChieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLichChieuChanging(string value);
    partial void OnmaLichChieuChanged();
    partial void OnmaPhimChanging(string value);
    partial void OnmaPhimChanged();
    partial void OnmaPhongChieuChanging(string value);
    partial void OnmaPhongChieuChanged();
    partial void OnngayChieuChanging(System.Nullable<System.DateTime> value);
    partial void OnngayChieuChanged();
    partial void OngioBDChanging(System.Nullable<System.TimeSpan> value);
    partial void OngioBDChanged();
    partial void OngioKTChanging(System.Nullable<System.TimeSpan> value);
    partial void OngioKTChanged();
    #endregion
		
		public LichChieu()
		{
			this._CT_Ves = new EntitySet<CT_Ve>(new Action<CT_Ve>(this.attach_CT_Ves), new Action<CT_Ve>(this.detach_CT_Ves));
			this._Phim = default(EntityRef<Phim>);
			this._PhongChieu = default(EntityRef<PhongChieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLichChieu", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLichChieu
		{
			get
			{
				return this._maLichChieu;
			}
			set
			{
				if ((this._maLichChieu != value))
				{
					this.OnmaLichChieuChanging(value);
					this.SendPropertyChanging();
					this._maLichChieu = value;
					this.SendPropertyChanged("maLichChieu");
					this.OnmaLichChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhim", DbType="VarChar(10)")]
		public string maPhim
		{
			get
			{
				return this._maPhim;
			}
			set
			{
				if ((this._maPhim != value))
				{
					if (this._Phim.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaPhimChanging(value);
					this.SendPropertyChanging();
					this._maPhim = value;
					this.SendPropertyChanged("maPhim");
					this.OnmaPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhongChieu", DbType="VarChar(10)")]
		public string maPhongChieu
		{
			get
			{
				return this._maPhongChieu;
			}
			set
			{
				if ((this._maPhongChieu != value))
				{
					if (this._PhongChieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaPhongChieuChanging(value);
					this.SendPropertyChanging();
					this._maPhongChieu = value;
					this.SendPropertyChanged("maPhongChieu");
					this.OnmaPhongChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayChieu", DbType="Date")]
		public System.Nullable<System.DateTime> ngayChieu
		{
			get
			{
				return this._ngayChieu;
			}
			set
			{
				if ((this._ngayChieu != value))
				{
					this.OnngayChieuChanging(value);
					this.SendPropertyChanging();
					this._ngayChieu = value;
					this.SendPropertyChanged("ngayChieu");
					this.OnngayChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioBD", DbType="Time")]
		public System.Nullable<System.TimeSpan> gioBD
		{
			get
			{
				return this._gioBD;
			}
			set
			{
				if ((this._gioBD != value))
				{
					this.OngioBDChanging(value);
					this.SendPropertyChanging();
					this._gioBD = value;
					this.SendPropertyChanged("gioBD");
					this.OngioBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioKT", DbType="Time")]
		public System.Nullable<System.TimeSpan> gioKT
		{
			get
			{
				return this._gioKT;
			}
			set
			{
				if ((this._gioKT != value))
				{
					this.OngioKTChanging(value);
					this.SendPropertyChanging();
					this._gioKT = value;
					this.SendPropertyChanged("gioKT");
					this.OngioKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichChieu_CT_Ve", Storage="_CT_Ves", ThisKey="maLichChieu", OtherKey="maLichChieu")]
		public EntitySet<CT_Ve> CT_Ves
		{
			get
			{
				return this._CT_Ves;
			}
			set
			{
				this._CT_Ves.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_LichChieu", Storage="_Phim", ThisKey="maPhim", OtherKey="maPhim", IsForeignKey=true)]
		public Phim Phim
		{
			get
			{
				return this._Phim.Entity;
			}
			set
			{
				Phim previousValue = this._Phim.Entity;
				if (((previousValue != value) 
							|| (this._Phim.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phim.Entity = null;
						previousValue.LichChieus.Remove(this);
					}
					this._Phim.Entity = value;
					if ((value != null))
					{
						value.LichChieus.Add(this);
						this._maPhim = value.maPhim;
					}
					else
					{
						this._maPhim = default(string);
					}
					this.SendPropertyChanged("Phim");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongChieu_LichChieu", Storage="_PhongChieu", ThisKey="maPhongChieu", OtherKey="maPhongChieu", IsForeignKey=true)]
		public PhongChieu PhongChieu
		{
			get
			{
				return this._PhongChieu.Entity;
			}
			set
			{
				PhongChieu previousValue = this._PhongChieu.Entity;
				if (((previousValue != value) 
							|| (this._PhongChieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongChieu.Entity = null;
						previousValue.LichChieus.Remove(this);
					}
					this._PhongChieu.Entity = value;
					if ((value != null))
					{
						value.LichChieus.Add(this);
						this._maPhongChieu = value.maPhongChieu;
					}
					else
					{
						this._maPhongChieu = default(string);
					}
					this.SendPropertyChanged("PhongChieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_Ves(CT_Ve entity)
		{
			this.SendPropertyChanging();
			entity.LichChieu = this;
		}
		
		private void detach_CT_Ves(CT_Ve entity)
		{
			this.SendPropertyChanging();
			entity.LichChieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiPhim")]
	public partial class LoaiPhim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maLoai;
		
		private string _tenLoai;
		
		private string _moTa;
		
		private EntitySet<Phim_LoaiPhim> _Phim_LoaiPhims;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLoaiChanging(string value);
    partial void OnmaLoaiChanged();
    partial void OntenLoaiChanging(string value);
    partial void OntenLoaiChanged();
    partial void OnmoTaChanging(string value);
    partial void OnmoTaChanged();
    #endregion
		
		public LoaiPhim()
		{
			this._Phim_LoaiPhims = new EntitySet<Phim_LoaiPhim>(new Action<Phim_LoaiPhim>(this.attach_Phim_LoaiPhims), new Action<Phim_LoaiPhim>(this.detach_Phim_LoaiPhims));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoai", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLoai
		{
			get
			{
				return this._maLoai;
			}
			set
			{
				if ((this._maLoai != value))
				{
					this.OnmaLoaiChanging(value);
					this.SendPropertyChanging();
					this._maLoai = value;
					this.SendPropertyChanged("maLoai");
					this.OnmaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLoai", DbType="NVarChar(255)")]
		public string tenLoai
		{
			get
			{
				return this._tenLoai;
			}
			set
			{
				if ((this._tenLoai != value))
				{
					this.OntenLoaiChanging(value);
					this.SendPropertyChanging();
					this._tenLoai = value;
					this.SendPropertyChanged("tenLoai");
					this.OntenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moTa", DbType="NVarChar(MAX)")]
		public string moTa
		{
			get
			{
				return this._moTa;
			}
			set
			{
				if ((this._moTa != value))
				{
					this.OnmoTaChanging(value);
					this.SendPropertyChanging();
					this._moTa = value;
					this.SendPropertyChanged("moTa");
					this.OnmoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiPhim_Phim_LoaiPhim", Storage="_Phim_LoaiPhims", ThisKey="maLoai", OtherKey="maLoai")]
		public EntitySet<Phim_LoaiPhim> Phim_LoaiPhims
		{
			get
			{
				return this._Phim_LoaiPhims;
			}
			set
			{
				this._Phim_LoaiPhims.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Phim_LoaiPhims(Phim_LoaiPhim entity)
		{
			this.SendPropertyChanging();
			entity.LoaiPhim = this;
		}
		
		private void detach_Phim_LoaiPhims(Phim_LoaiPhim entity)
		{
			this.SendPropertyChanging();
			entity.LoaiPhim = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNhanVien;
		
		private string _tenNhanVien;
		
		private string _diaChi;
		
		private string _email;
		
		private string _SDT;
		
		private EntitySet<TaiKhoan> _TaiKhoans;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OntenNhanVienChanging(string value);
    partial void OntenNhanVienChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
		
		public NhanVien()
		{
			this._TaiKhoans = new EntitySet<TaiKhoan>(new Action<TaiKhoan>(this.attach_TaiKhoans), new Action<TaiKhoan>(this.detach_TaiKhoans));
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNhanVien", DbType="NVarChar(255)")]
		public string tenNhanVien
		{
			get
			{
				return this._tenNhanVien;
			}
			set
			{
				if ((this._tenNhanVien != value))
				{
					this.OntenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._tenNhanVien = value;
					this.SendPropertyChanged("tenNhanVien");
					this.OntenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(255)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(255)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(15)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaiKhoan", Storage="_TaiKhoans", ThisKey="maNhanVien", OtherKey="maNhanVien")]
		public EntitySet<TaiKhoan> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon", Storage="_HoaDons", ThisKey="maNhanVien", OtherKey="maNV")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien_ChucVu")]
	public partial class NhanVien_ChucVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _tenDangNhap;
		
		private string _maChucVu;
		
		private EntityRef<ChucVu> _ChucVu;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntenDangNhapChanging(string value);
    partial void OntenDangNhapChanged();
    partial void OnmaChucVuChanging(string value);
    partial void OnmaChucVuChanged();
    #endregion
		
		public NhanVien_ChucVu()
		{
			this._ChucVu = default(EntityRef<ChucVu>);
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenDangNhap", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string tenDangNhap
		{
			get
			{
				return this._tenDangNhap;
			}
			set
			{
				if ((this._tenDangNhap != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._tenDangNhap = value;
					this.SendPropertyChanged("tenDangNhap");
					this.OntenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maChucVu", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maChucVu
		{
			get
			{
				return this._maChucVu;
			}
			set
			{
				if ((this._maChucVu != value))
				{
					if (this._ChucVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaChucVuChanging(value);
					this.SendPropertyChanging();
					this._maChucVu = value;
					this.SendPropertyChanged("maChucVu");
					this.OnmaChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_NhanVien_ChucVu", Storage="_ChucVu", ThisKey="maChucVu", OtherKey="maChucVu", IsForeignKey=true)]
		public ChucVu ChucVu
		{
			get
			{
				return this._ChucVu.Entity;
			}
			set
			{
				ChucVu previousValue = this._ChucVu.Entity;
				if (((previousValue != value) 
							|| (this._ChucVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChucVu.Entity = null;
						previousValue.NhanVien_ChucVus.Remove(this);
					}
					this._ChucVu.Entity = value;
					if ((value != null))
					{
						value.NhanVien_ChucVus.Add(this);
						this._maChucVu = value.maChucVu;
					}
					else
					{
						this._maChucVu = default(string);
					}
					this.SendPropertyChanged("ChucVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_NhanVien_ChucVu", Storage="_TaiKhoan", ThisKey="tenDangNhap", OtherKey="tenDangNhap", IsForeignKey=true)]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.NhanVien_ChucVus.Remove(this);
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.NhanVien_ChucVus.Add(this);
						this._tenDangNhap = value.tenDangNhap;
					}
					else
					{
						this._tenDangNhap = default(string);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanQuyen")]
	public partial class PhanQuyen
	{
		
		private string _maChucVu;
		
		private string _maManHinh;
		
		private int _coQuyen;
		
		public PhanQuyen()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maChucVu", DbType="VarChar(10)")]
		public string maChucVu
		{
			get
			{
				return this._maChucVu;
			}
			set
			{
				if ((this._maChucVu != value))
				{
					this._maChucVu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maManHinh", DbType="VarChar(10)")]
		public string maManHinh
		{
			get
			{
				return this._maManHinh;
			}
			set
			{
				if ((this._maManHinh != value))
				{
					this._maManHinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coQuyen", DbType="Int NOT NULL")]
		public int coQuyen
		{
			get
			{
				return this._coQuyen;
			}
			set
			{
				if ((this._coQuyen != value))
				{
					this._coQuyen = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phim")]
	public partial class Phim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maPhim;
		
		private string _tenPhim;
		
		private System.Nullable<int> _thoiLuong;
		
		private string _daoDien;
		
		private string _quocGia;
		
		private string _noiDung;
		
		private string _hinhAnh;
		
		private System.Nullable<System.DateTime> _ngayChieu;
		
		private System.Nullable<System.DateTime> _ngayKT;
		
		private System.Nullable<int> _trangThai;
		
		private EntitySet<LichChieu> _LichChieus;
		
		private EntitySet<Phim_LoaiPhim> _Phim_LoaiPhims;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaPhimChanging(string value);
    partial void OnmaPhimChanged();
    partial void OntenPhimChanging(string value);
    partial void OntenPhimChanged();
    partial void OnthoiLuongChanging(System.Nullable<int> value);
    partial void OnthoiLuongChanged();
    partial void OndaoDienChanging(string value);
    partial void OndaoDienChanged();
    partial void OnquocGiaChanging(string value);
    partial void OnquocGiaChanged();
    partial void OnnoiDungChanging(string value);
    partial void OnnoiDungChanged();
    partial void OnhinhAnhChanging(string value);
    partial void OnhinhAnhChanged();
    partial void OnngayChieuChanging(System.Nullable<System.DateTime> value);
    partial void OnngayChieuChanged();
    partial void OnngayKTChanging(System.Nullable<System.DateTime> value);
    partial void OnngayKTChanged();
    partial void OntrangThaiChanging(System.Nullable<int> value);
    partial void OntrangThaiChanged();
    #endregion
		
		public Phim()
		{
			this._LichChieus = new EntitySet<LichChieu>(new Action<LichChieu>(this.attach_LichChieus), new Action<LichChieu>(this.detach_LichChieus));
			this._Phim_LoaiPhims = new EntitySet<Phim_LoaiPhim>(new Action<Phim_LoaiPhim>(this.attach_Phim_LoaiPhims), new Action<Phim_LoaiPhim>(this.detach_Phim_LoaiPhims));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhim", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maPhim
		{
			get
			{
				return this._maPhim;
			}
			set
			{
				if ((this._maPhim != value))
				{
					this.OnmaPhimChanging(value);
					this.SendPropertyChanging();
					this._maPhim = value;
					this.SendPropertyChanged("maPhim");
					this.OnmaPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenPhim", DbType="NVarChar(255)")]
		public string tenPhim
		{
			get
			{
				return this._tenPhim;
			}
			set
			{
				if ((this._tenPhim != value))
				{
					this.OntenPhimChanging(value);
					this.SendPropertyChanging();
					this._tenPhim = value;
					this.SendPropertyChanged("tenPhim");
					this.OntenPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiLuong", DbType="Int")]
		public System.Nullable<int> thoiLuong
		{
			get
			{
				return this._thoiLuong;
			}
			set
			{
				if ((this._thoiLuong != value))
				{
					this.OnthoiLuongChanging(value);
					this.SendPropertyChanging();
					this._thoiLuong = value;
					this.SendPropertyChanged("thoiLuong");
					this.OnthoiLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daoDien", DbType="NVarChar(255)")]
		public string daoDien
		{
			get
			{
				return this._daoDien;
			}
			set
			{
				if ((this._daoDien != value))
				{
					this.OndaoDienChanging(value);
					this.SendPropertyChanging();
					this._daoDien = value;
					this.SendPropertyChanged("daoDien");
					this.OndaoDienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quocGia", DbType="NVarChar(255)")]
		public string quocGia
		{
			get
			{
				return this._quocGia;
			}
			set
			{
				if ((this._quocGia != value))
				{
					this.OnquocGiaChanging(value);
					this.SendPropertyChanging();
					this._quocGia = value;
					this.SendPropertyChanged("quocGia");
					this.OnquocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiDung", DbType="NVarChar(MAX)")]
		public string noiDung
		{
			get
			{
				return this._noiDung;
			}
			set
			{
				if ((this._noiDung != value))
				{
					this.OnnoiDungChanging(value);
					this.SendPropertyChanging();
					this._noiDung = value;
					this.SendPropertyChanged("noiDung");
					this.OnnoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhAnh", DbType="NVarChar(255)")]
		public string hinhAnh
		{
			get
			{
				return this._hinhAnh;
			}
			set
			{
				if ((this._hinhAnh != value))
				{
					this.OnhinhAnhChanging(value);
					this.SendPropertyChanging();
					this._hinhAnh = value;
					this.SendPropertyChanged("hinhAnh");
					this.OnhinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayChieu", DbType="Date")]
		public System.Nullable<System.DateTime> ngayChieu
		{
			get
			{
				return this._ngayChieu;
			}
			set
			{
				if ((this._ngayChieu != value))
				{
					this.OnngayChieuChanging(value);
					this.SendPropertyChanging();
					this._ngayChieu = value;
					this.SendPropertyChanged("ngayChieu");
					this.OnngayChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayKT", DbType="Date")]
		public System.Nullable<System.DateTime> ngayKT
		{
			get
			{
				return this._ngayKT;
			}
			set
			{
				if ((this._ngayKT != value))
				{
					this.OnngayKTChanging(value);
					this.SendPropertyChanging();
					this._ngayKT = value;
					this.SendPropertyChanged("ngayKT");
					this.OnngayKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Int")]
		public System.Nullable<int> trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_LichChieu", Storage="_LichChieus", ThisKey="maPhim", OtherKey="maPhim")]
		public EntitySet<LichChieu> LichChieus
		{
			get
			{
				return this._LichChieus;
			}
			set
			{
				this._LichChieus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_Phim_LoaiPhim", Storage="_Phim_LoaiPhims", ThisKey="maPhim", OtherKey="maPhim")]
		public EntitySet<Phim_LoaiPhim> Phim_LoaiPhims
		{
			get
			{
				return this._Phim_LoaiPhims;
			}
			set
			{
				this._Phim_LoaiPhims.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichChieus(LichChieu entity)
		{
			this.SendPropertyChanging();
			entity.Phim = this;
		}
		
		private void detach_LichChieus(LichChieu entity)
		{
			this.SendPropertyChanging();
			entity.Phim = null;
		}
		
		private void attach_Phim_LoaiPhims(Phim_LoaiPhim entity)
		{
			this.SendPropertyChanging();
			entity.Phim = this;
		}
		
		private void detach_Phim_LoaiPhims(Phim_LoaiPhim entity)
		{
			this.SendPropertyChanging();
			entity.Phim = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phim_LoaiPhim")]
	public partial class Phim_LoaiPhim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maPhim;
		
		private string _maLoai;
		
		private EntityRef<LoaiPhim> _LoaiPhim;
		
		private EntityRef<Phim> _Phim;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaPhimChanging(string value);
    partial void OnmaPhimChanged();
    partial void OnmaLoaiChanging(string value);
    partial void OnmaLoaiChanged();
    #endregion
		
		public Phim_LoaiPhim()
		{
			this._LoaiPhim = default(EntityRef<LoaiPhim>);
			this._Phim = default(EntityRef<Phim>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhim", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maPhim
		{
			get
			{
				return this._maPhim;
			}
			set
			{
				if ((this._maPhim != value))
				{
					if (this._Phim.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaPhimChanging(value);
					this.SendPropertyChanging();
					this._maPhim = value;
					this.SendPropertyChanged("maPhim");
					this.OnmaPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoai", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLoai
		{
			get
			{
				return this._maLoai;
			}
			set
			{
				if ((this._maLoai != value))
				{
					if (this._LoaiPhim.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLoaiChanging(value);
					this.SendPropertyChanging();
					this._maLoai = value;
					this.SendPropertyChanged("maLoai");
					this.OnmaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiPhim_Phim_LoaiPhim", Storage="_LoaiPhim", ThisKey="maLoai", OtherKey="maLoai", IsForeignKey=true)]
		public LoaiPhim LoaiPhim
		{
			get
			{
				return this._LoaiPhim.Entity;
			}
			set
			{
				LoaiPhim previousValue = this._LoaiPhim.Entity;
				if (((previousValue != value) 
							|| (this._LoaiPhim.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiPhim.Entity = null;
						previousValue.Phim_LoaiPhims.Remove(this);
					}
					this._LoaiPhim.Entity = value;
					if ((value != null))
					{
						value.Phim_LoaiPhims.Add(this);
						this._maLoai = value.maLoai;
					}
					else
					{
						this._maLoai = default(string);
					}
					this.SendPropertyChanged("LoaiPhim");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_Phim_LoaiPhim", Storage="_Phim", ThisKey="maPhim", OtherKey="maPhim", IsForeignKey=true)]
		public Phim Phim
		{
			get
			{
				return this._Phim.Entity;
			}
			set
			{
				Phim previousValue = this._Phim.Entity;
				if (((previousValue != value) 
							|| (this._Phim.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phim.Entity = null;
						previousValue.Phim_LoaiPhims.Remove(this);
					}
					this._Phim.Entity = value;
					if ((value != null))
					{
						value.Phim_LoaiPhims.Add(this);
						this._maPhim = value.maPhim;
					}
					else
					{
						this._maPhim = default(string);
					}
					this.SendPropertyChanged("Phim");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhongChieu")]
	public partial class PhongChieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maPhongChieu;
		
		private string _tenPhongChieu;
		
		private System.Nullable<int> _soLuongGhe;
		
		private EntitySet<Ghe> _Ghes;
		
		private EntitySet<LichChieu> _LichChieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaPhongChieuChanging(string value);
    partial void OnmaPhongChieuChanged();
    partial void OntenPhongChieuChanging(string value);
    partial void OntenPhongChieuChanged();
    partial void OnsoLuongGheChanging(System.Nullable<int> value);
    partial void OnsoLuongGheChanged();
    #endregion
		
		public PhongChieu()
		{
			this._Ghes = new EntitySet<Ghe>(new Action<Ghe>(this.attach_Ghes), new Action<Ghe>(this.detach_Ghes));
			this._LichChieus = new EntitySet<LichChieu>(new Action<LichChieu>(this.attach_LichChieus), new Action<LichChieu>(this.detach_LichChieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhongChieu", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maPhongChieu
		{
			get
			{
				return this._maPhongChieu;
			}
			set
			{
				if ((this._maPhongChieu != value))
				{
					this.OnmaPhongChieuChanging(value);
					this.SendPropertyChanging();
					this._maPhongChieu = value;
					this.SendPropertyChanged("maPhongChieu");
					this.OnmaPhongChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenPhongChieu", DbType="NVarChar(255)")]
		public string tenPhongChieu
		{
			get
			{
				return this._tenPhongChieu;
			}
			set
			{
				if ((this._tenPhongChieu != value))
				{
					this.OntenPhongChieuChanging(value);
					this.SendPropertyChanging();
					this._tenPhongChieu = value;
					this.SendPropertyChanged("tenPhongChieu");
					this.OntenPhongChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuongGhe", DbType="Int")]
		public System.Nullable<int> soLuongGhe
		{
			get
			{
				return this._soLuongGhe;
			}
			set
			{
				if ((this._soLuongGhe != value))
				{
					this.OnsoLuongGheChanging(value);
					this.SendPropertyChanging();
					this._soLuongGhe = value;
					this.SendPropertyChanged("soLuongGhe");
					this.OnsoLuongGheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongChieu_Ghe", Storage="_Ghes", ThisKey="maPhongChieu", OtherKey="maPhongChieu")]
		public EntitySet<Ghe> Ghes
		{
			get
			{
				return this._Ghes;
			}
			set
			{
				this._Ghes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongChieu_LichChieu", Storage="_LichChieus", ThisKey="maPhongChieu", OtherKey="maPhongChieu")]
		public EntitySet<LichChieu> LichChieus
		{
			get
			{
				return this._LichChieus;
			}
			set
			{
				this._LichChieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ghes(Ghe entity)
		{
			this.SendPropertyChanging();
			entity.PhongChieu = this;
		}
		
		private void detach_Ghes(Ghe entity)
		{
			this.SendPropertyChanging();
			entity.PhongChieu = null;
		}
		
		private void attach_LichChieus(LichChieu entity)
		{
			this.SendPropertyChanging();
			entity.PhongChieu = this;
		}
		
		private void detach_LichChieus(LichChieu entity)
		{
			this.SendPropertyChanging();
			entity.PhongChieu = null;
		}
	}
}
#pragma warning restore 1591
