//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("triss")]
        public string strConn {
            get {
                return ((string)(this["strConn"]));
            }
            set {
                this["strConn"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-OTH2ANP\\SQLEXPRESS;Initial Catalog=QL_RAPCHIEUPHIM;User ID=sa" +
            ";Password=123456")]
        public string QL_RAPCHIEUPHIMConnectionString {
            get {
                return ((string)(this["QL_RAPCHIEUPHIMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-OTH2ANP\\SQLEXPRESS;Initial Catalog=QL_RAPCHIEUPHIM;Persist Se" +
            "curity Info=True;User ID=sa;Password=123456")]
        public string QL_RAPCHIEUPHIMConnectionString1 {
            get {
                return ((string)(this["QL_RAPCHIEUPHIMConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-OTH2ANP\\SQLEXPRESS;Initial Catalog=QL_RAPCHIEUPHIM1;User ID=s" +
            "a;Password=123456;Encrypt=False")]
        public string QL_RAPCHIEUPHIM1ConnectionString {
            get {
                return ((string)(this["QL_RAPCHIEUPHIM1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-OTH2ANP\\SQLEXPRESS;Initial Catalog=QL_RAPCHIEUPHIM2;User ID=s" +
            "a;Password=123456;Encrypt=False")]
        public string QL_RAPCHIEUPHIM2ConnectionString {
            get {
                return ((string)(this["QL_RAPCHIEUPHIM2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-OTH2ANP\\SQLEXPRESS;Initial Catalog=QL_RAPCHIEUPHIM3;User ID=s" +
            "a;Password=123456;Encrypt=False")]
        public string QL_RAPCHIEUPHIM3ConnectionString {
            get {
                return ((string)(this["QL_RAPCHIEUPHIM3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-SNLG86J\\SQLEXPRESS;Initial Catalog=QL_RAPCHIEUPHIMTEST;User I" +
            "D=sa;Password=123456;Encrypt=False")]
        public string QL_RAPCHIEUPHIMTESTConnectionString {
            get {
                return ((string)(this["QL_RAPCHIEUPHIMTESTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\;Initial Catalog=QL_RAPCHIEUPHIM5;Integrated Security=True;Encrypt=" +
            "False")]
        public string QL_RAPCHIEUPHIM5ConnectionString {
            get {
                return ((string)(this["QL_RAPCHIEUPHIM5ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\;Initial Catalog=QL_RAPCHIEUPHIM;Integrated Security=True;Encrypt=F" +
            "alse")]
        public string QL_RAPCHIEUPHIMConnectionString2 {
            get {
                return ((string)(this["QL_RAPCHIEUPHIMConnectionString2"]));
            }
        }
    }
}
